import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  card: {
    width: 360,
    height: 480,
    backgroundColor: 'white',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomLeftRadius: 7,
    borderBottomRightRadius: 7,
    marginTop: 45,
  },
  noMoreCardsText: {
    fontSize: 22,
  },
  image: {
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    flex: 1,
    alignSelf: 'stretch',
    width: undefined,
    height: undefined,
  },
  cardName: {
    color: '#000000',
    fontWeight: 'bold',
    fontSize: 22,
    bottom: 3,
    left: 8,
  },
  cardText: {
    color: '#2c2c2c',
    fontSize: 18,
    bottom: 3,
    left: 8,
  },
  background: {
    justifyContent: 'center',
    flex: 10,
  },
  logo: {
    alignSelf: 'center',
    width: 260,
    height: 70,
  },
  welcome: {
    fontFamily: 'sans-serif-medium',
    color: 'white',
    fontSize: 20,
    alignSelf: 'center',
    textAlign: 'center',
    maxWidth: '80%',
  },
  start: {
    fontFamily: 'sans-serif-medium',
    fontSize: 20,
    color: '#333',
  },
  zip: {
    alignSelf: 'center',
    width: '32%',
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    borderRadius: 5,
    marginBottom: '2%',
  },
  button: {
    alignSelf: 'center',
    width: 200,
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    borderRadius: 5,
    padding: 8,
  },
  divider: {
    marginBottom: 1,
  },
  favoriteImage: {
    top: 5.5,
    left: 10,
    width: 150,
    height: 140,
    borderRadius: 5,
  },
  favoriteName: {
    fontWeight: 'bold',
    left: 170,
    bottom: 130,
  },
  favoriteDesc: {
    left: 170,
    bottom: 128,
  },
  favoriteTitle: {
    color: 'white',
    fontSize: 20,
    textAlign: 'center',
    bottom: '35%',
  },
  noAnimals: {
    textAlign: 'center',
    color: '#303030',
    textAlignVertical: 'center',
    fontSize: 36,
    top: '70%',
  },
  noAnimalsTitle: {
    textAlign: 'center',
    color: '#303030',
    textAlignVertical: 'center',
    fontSize: 36,
    top: '70%',
    marginBottom: 5,
  },
  container: {
    marginTop: '5%',
    height: '100%',
    width: '90%',
    alignSelf: 'center',
    alignItems: 'center',
  },
  options: {
    alignSelf: 'center',
    flexDirection: 'row',
    flex: 1,
    paddingTop: 10,
    paddingBottom: 10,
  },
  options2: {
    flex: 1,
  },
  optionsRow: {
    alignSelf: 'center',
    flexDirection: 'row',
    paddingBottom: 10,
  },
  petfinder: {
    height: 50,
    width: 120,
    alignSelf: 'center',
  },
  descName: {
    alignSelf: 'center',
    fontWeight: 'bold',
    fontSize: 22,
    color: '#303030',
    top: '1%',
  },
  descBreed: {
    alignSelf: 'center',
    top: '1%',
    fontSize: 20,
  },
  descDesc: {
    alignSelf: 'center',
    top: '1%',
    fontSize: 20,
  },
  viewMaps: {
    width: 200,
    marginTop: '7%',
    marginBottom: '5%',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#303030',
    borderRadius: 5,
    padding: 8,
  },
  viewText: {
    fontFamily: 'sans-serif-medium',
    fontSize: 20,
    color: 'white',
  },
  description: {
    fontSize: 17,
    top: '2.5%',
    marginBottom: '7%',
    alignSelf: 'center',
  },
  phone: {
    marginTop: '5%',
    marginBottom: '2%',
    fontSize: 17,
    alignSelf: 'center',
    color: '#007aff',
  },
  email: {
    fontSize: 17,
    alignSelf: 'center',
    color: '#007aff',
  },
});
